### ISSUE TITLE
ServerException when no results to return

### ISSUE THREAD

**Issue by idoadiv** [PommeVerte/gremlin-php#15]
Seems like odd behaviour, is it intentional?

**Comment by PommeVerte** [comment]
Yes it's intentional. 
The server throws an exception and the driver just propagates the exception. There were lengthy discussion about this on the gremlin-user and apache TinkerPop dev mailing lists. The gist of it was that the server's `FastNoSuchElementException` should stay as it provides an explicit error for users who make incorrect requests. If it were removed, debugging long scripts could be very difficult.

The reason why the driver just propagates the error is because I never intended it to be anything other than a driver, it simply parses and returns the results from the database, exceptions and all.

You can easily enforce the "correct" behavior of returning an empty result set with : 
```php
try 
{
   $result = $db->send("g.V().has('doesNotExist')");
} 
catch(\Brightzone\GremlinDriver\ServerException $e) 
{
   if($e->getCode() == 204)
   {
       $result = [];
   } 
   else 
   {
       throw $e;
   }
}
```

**Comment by PommeVerte** [comment]
Closing this but feel free to share your thoughts here. I understand that this behavior isn't intuitive and goes against most of what we're used to with databases. But once you wrap the driver it isn't much of an issue anymore.

**Comment by PommeVerte** [comment]
FYI. I added an extra feature in `2.2.0`. Now you can configure your `Connection` class with a `emptySet` property to get empty result sets instead of an exception.

Example: 
```php
$db = new Connection([
   'emptySet' => TRUE // will return [] for empty result sets.
]);
$result = $db->send("g.V().has('notexist')");
print_r($result); // prints Array()
```

I still encourage you *not to use this* and instead apply a try-catch strategy as that may really help with debugging further down the line. 
If your use case is simple enough and you want the added performance related to avoiding try-catch then know that you can do this via the driver now.
