### ISSUE TITLE
do you plan to add OGM support?

### ISSUE THREAD

**Issue by softwarevamp** [PommeVerte/gremlin-php#29]
as titled, thanks.

**Comment by PommeVerte** [comment]
Hey. Sorry for the delay, I didn't get a notification for this. A little strange. 

There are no plans for an OGM layer. Mostly because the php ecosystem is often framework centric and each an every one has their own Objects (ActiveRecords/etc).
TinkerPop is slowly moving towards Gremlin Language Variants though so there will likely be an OGM layer to those once we get around to working on the PHP version.

Cheers.
