### ISSUE TITLE
Cannot Try Catch DB->Connection->Open

### ISSUE THREAD

**Issue by The-Don-Himself** [PommeVerte/gremlin-php#37]
````
        try {
            $db->open();
        } catch (\Brightzone\GremlinDriver\InternalException $e) {
            $error_message = $e->getMessage());
        }
````

This command fails to catch the thrown exception.

Tested on PHP 7.1+

Further debugging shows the error occurs https://github.com/PommeVerte/gremlin-php/blob/master/src/Connection.php#L370-L377

at command $this->_socket = @stream_socket_client ...

Setting this to a variable first fixes it, will submit a PR shortly but would love an explanation from those who know why :)

````
        $fp = @stream_socket_client(
                                    $protocol. '://' . $this->host .':'.$this->port,
                                    $errno,
                                    $errorMessage,
                                    $this->timeout ? $this->timeout : ini_get("default_socket_timeout"),
                                    STREAM_CLIENT_CONNECT,
                                    $context
                                    );

        if(!$fp){
            $this->error($errorMessage, $errno, TRUE);
        }

        $this->_socket = $fp;
````

**Comment by PommeVerte** [comment]
Hey,

I'm still trying to figure out what the issue is here.
I'm trying to recreate it but to no avail, all the tests seem to work fine. I'm running : 
```
PHP 7.1.8 (cli) (built: Aug 30 2017 23:51:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
````
Are you using a custom compiled build? 
Can you try running the following test on ab0e5b654c5cbe671e1e9572663830f8545e77f1 and let me know what you get?

```bash
vendor/bin/phpunit --filter testConnectErrorsUnknnownHost --conf build/phpunit.xml 
```

If you couldn't catch the error that test should fail. If it doesn't, can you write a quick snippet that does fail? I worry that there may be other scenarios that could fail from something like this (all the socket streaming operations really)

Thanks.

In the meantime I will add your PR changes to the latest release.

**Comment by The-Don-Himself** [comment]
On Local Machine
````
C:\wamp64\www\campus-discounts.com>php -v
PHP 7.1.8 (cli) (built: Aug  1 2017 20:56:53) ( ZTS MSVC14 (Visual C++ 2015) x64
 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
````

On production server
````
[don@Symfony ~]$ php -v
PHP 7.1.8 (cli) (built: Aug  2 2017 12:13:05) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.8, Copyright (c) 1999-2017, by Zend Technologies
````

I'm not using any custom build in my view, although, to get the latest PHP versions on Centos I use the REMI repos while to do the same on Windows I use http://wampserver.aviatechno.net/

Let me ask, does the slight change in the PR make any sense on why or how it could cause the Exception not to be caught?

**Comment by PommeVerte** [comment]
Not that I can tell (especially not considering it seems to work fine on my end). I'm curious to know what `$this->_socket` is set to when it bypasses the `if` statement. 

I'm going to try the wamp server and check there.

**Comment by The-Don-Himself** [comment]
Typing from mobile so pardon any error.

I'll try set up a temporary VPS and install the necessary packages to reproduce. If it does, I'll send you the credentials.

One thing that has just come to mind is that I use this package inside Symfony, perhaps the error comes from that as well. However, it should be noted that it shows up both in a Symfony controller executed by Apache and the Symfony console executed via CLI.

**Comment by PommeVerte** [comment]
I've just managed to recreate it using wamp server :)

**Comment by The-Don-Himself** [comment]
Great, you'd realise that the PR fixes it and while I don't know much of PHP internals I'll be interested in knowing why.

**Comment by PommeVerte** [comment]
Ok I figured this one out. Kinda twisted, and also a bug in the driver across all php versions.

`$this->_socket` was being set to `false` by the failing `@stream_socket_client`. The driver automatically tries to close the connection if it's live on `__destruct()`. 
The `close()` operation sees the socket set to something other than `null` and tries to close it but it then implodes. Because that error comes from the class destructor it isn't caught by your try/catch block.

**Comment by The-Don-Himself** [comment]
Awesome, especially the explanation. Makes a lot of sense and made me learn something, notwithstanding the PR advice, it's been a good learning week :)
Glad I could be of help, I've actually been hoping to make a GraphDB Symfon Bundle from this Lib when I get time.
Guess I can close this then?
