### ISSUE TITLE
Certain commands return nothing

### ISSUE THREAD

**Issue by juhasev** [PommeVerte/gremlin-php#49]
I am running into an issue with 

g.V().drop()

which would drop all vertices. None of the drop queries work for some reason... Once you add iterate() this is supposed to work.

g.V().drop().iterate()

These work fine in Gremlin console but not via PHP.

Running JanusGraph 0.2.0 (w/ Cassandra & ElasticSearch) with bundled gremlin server.

From GremlinServer logs:
```
87565089 [gremlin-server-worker-1] INFO  org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor  - Initialized gremlin-groovy ScriptEngine with scripts/empty-sample.groovy
87565112 [gremlin-server-session-1] WARN  org.janusgraph.graphdb.transaction.StandardJanusGraphTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
87565146 [gremlin-server-worker-1] INFO  org.apache.tinkerpop.gremlin.server.op.session.Session  - Session 22a0f71e-433f-4441-b804-5392101c7f74 closed
```

**Comment by PommeVerte** [comment]
Are you saying that both `g.V().drop()` and `g.V().drop().iterate()` are failing in php?
Can you let me know what version of the gremlin-php driver you are using as well? And how you're sending the request (using `Connection::send()` or `Connection::run()`?)

Bellow is some info I gathered up concerning the setup. Let me know if there's anything out of place:

- JanusGraph `0.2.0` seems to be using tinkerpop `3.2.8`
- [gremlin-server.yaml](https://github.com/JanusGraph/janusgraph/blob/0.2/janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml)
- [janusgraph-cassandra-es-server.properties](https://github.com/JanusGraph/janusgraph/blob/0.2/janusgraph-dist/src/assembly/static/conf/gremlin-server/janusgraph-cassandra-es-server.properties)

**Comment by juhasev** [comment]
Didn't know about the run method! It works with it just fine. We should add that to the documentation and also mention requirement for using next() to get v extracted from a method. Like:

snowboarding = g.addV("hobby").property("name","Snow Boarding").next()

fails without the next(). All examples are written for gremlin console and there seems to be a lot of differences how things need to be approached. This is my first real journey to Gremlin.

**Comment by PommeVerte** [comment]
Yeah seems like there are a few things worth noting. Some of which I should definitely add to the documentation.

### Empty return error
There is such a thing as an "empty return error". This is how it's communicated back from the server and hasn't been changed on the TinkerPop end because it is (or has been) very useful for debugging purposes. This error just means the server isn't returning any info. It's not really an error so to speak. 

Because the driver bubbles up server issues, any empty return value will throw a similar error on the php end (`ServerException code 204`). It is worth noting that even though you get this error your code is still being executed.
The reason why you get no error on `Connection::run()` is that run ignores any info returned from the server by default. Just sends and forgets.

People implementing the driver should consider doing one of two things : 
```php
$db = new Connection([
     // ... config here ...
]);
$db->open();
try {
   $db->send("g.V().drop()");
} catch ($e)
{
   if($e instanceof ServerException && $e->getCode() == 204) {
      return [];
   } else {
      throw $e;
   }
}
```
The other option is 
```php
$db = new Connection([
     "emptySet" => true, // this will automatically send you an empty array in place of an error.
     // ... config here ...
]);
```

### Iterations
The way the console works is that it automatically iterates your queries. It's a comfort feature. Unfortunately whether it be gremlin sent through drivers or in native java you need to do those iterations manually. 
It's very misleading because most/all the documentation is done using gremlin console.

**Comment by PommeVerte** [comment]
Let me know if you think of a good way of structuring the documentation to mention these points. 
Also just to reiterate, you should be using `Connection::send()` in your case if you care at all about potential server side errors (like server side transaction conflicts)

**Comment by juhasev** [comment]
Great comments. I totally agree. This has been rather confusing experience due to lack of documentation / relatively small community. Even Tinkerpop 3 docs are outdated right at the tutorial. Need to find some good cook book / reference on this.

**Comment by PommeVerte** [comment]
I just skimmed it but this looked like a good guide : http://kelvinlawrence.net/book/Gremlin-Graph-Guide.html It won't make any mentions of iterations but you can pretty much ask here or on the gremlin user list if you have any questions regarding that. 
Otherwise going to the "1. Reference Documentation > The Traversal section" for the correct TinkerPop version is often good too. Look [here](http://tinkerpop.apache.org/docs/) (Janus graph 0.2.0 uses TinkerPop 3.2.8)

If you have any questions on the driver or gremlin in general feel free to create a new issue. I'll keep this open as a reminder to edit the documentation a bit. Maybe a quick start guide might be useful.

**Comment by juhasev** [comment]
I discovered his book yesterday and it is indeed best Gremlin guide out there. Thanks for the help!
